FROM mcr.microsoft.com/vscode/devcontainers/universal:latest

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y clang-10 clang-11 libstdc++-10-dev libcurl4-openssl-dev libssl-dev ninja-build
